### ISSUE TITLE
binary lists

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#179] opened 2019-04-22 21:51 UTC
Binary parser breaks towards the end of a list. Users reported being able to read 8/10 values but failed to return the final two blobs.

**Comment by pbcornell** [comment] 2019-07-18 23:28
Investigate and update sizing if appropriate.

**Comment by pbcornell** [comment] 2019-07-26 00:43
Need more info to reproduce this issue.  The following code represents my attempt to reproduce, but it behaves as I expect it to.  Perhaps the blob values aren't sufficiently 'interesting'?

See below for the error it produces when numBlobs is 50,000.

```javascript
let numBlobs = 10;                // works fine at 25,000;  error when set to 50,000
let writer = ion.makeBinaryWriter();
writer.writeList();
for (let i = 0; i < numBlobs; i++) {
    let sb = i+'';
    for (let j = 0; j < 1000; j++) {
        sb += Math.random().toString(36).substring(7);
    }
    writer.writeBlob(Buffer.from(sb, 'utf8'));
}
writer.endContainer();
writer.close();
let ionBinary = writer.getBytes();

let binaryReader = ion.makeReader(ionBinary);
traverse(binaryReader);

function traverse(reader: IonReader) {
    let count = 0;
    for (let type; type = reader.next(); ) {
        count++;
        if (type.container && !reader.isNull()) {
            writeln(type.name + ' stepIn');
            reader.stepIn();
            traverse(reader);
            reader.stepOut();
            writeln(type.name + ' stepOut');
        } else {
            //writeln(type.name + ': ' + reader.value());
        }
    }
    writeln('count: ' + count);
}
```

When numBlobs is 50,000, the following error is (eventually) produced, although this looks like a different issue:
```
Error: VarUInt values larger than 31 bits must be read using LongInt.
  at Function.readVarUnsignedIntFrom @ ../ion-js.development/src/IonParserBinaryRaw.ts:173:18
  at ParserBinaryRaw.readVarUnsignedInt @ ../ion-js.development/src/IonParserBinaryRaw.ts:180:31
  at ParserBinaryRaw.load_length @ ../ion-js.development/src/IonParserBinaryRaw.ts:359:30
  at ParserBinaryRaw.load_next @ ../ion-js.development/src/IonParserBinaryRaw.ts:382:10
  at ParserBinaryRaw.next @ ../ion-js.development/src/IonParserBinaryRaw.ts:518:20
  at BinaryReader.next @ ../ion-js.development/src/IonBinaryReader.ts:98:101
  at traverse @ tests/reproductions.ts:314:33
  at Object.<anonymous> @ tests/reproductions.ts:310:0
  at Module._compile @ internal/modules/cjs/loader.js:701:30
  at Object.Module._extensions..js @ internal/modules/cjs/loader.js:712:10
  at Module.load @ node_modules/coffeescript/lib/coffee-script/register.js:45:36
  at tryModuleLoad @ internal/modules/cjs/loader.js:539:12
  at Function.Module._load @ internal/modules/cjs/loader.js:531:3
  at Module.require @ internal/modules/cjs/loader.js:637:17
  at require @ internal/modules/cjs/helpers.js:22:18
  at Node.loadScript @ src/lib/executors/Node.ts:238:10
  at Node._loader @ src/loaders/default.ts:10:18
  at Node.BaseExecutor._loadSuites @ src/lib/executors/Executor.ts:976:29
  at Node._loadSuites @ src/lib/executors/Node.ts:584:28
  @ src/lib/executors/Executor.ts:667:29
  @ node_modules/@theintern/common/index.js:16:7182
  at process._tickCallback @ internal/process/next_tick.js:68:7
```

**Comment by pbcornell** [comment] 2019-08-05 19:42
Unable to reproduce; closing

**Closed by pbcornell** 2019-08-05 19:42 UTC
Labels: S, bucketing
