### ISSUE TITLE
Binary FieldNames

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#166] opened 2018-07-16 22:32 UTC
Keyword false returns undefined

**Comment by pbcornell** [comment] 2019-07-18 21:51
Try to reproduce:
- create a binary writer
- write a struct with a field name `false`
- attempt to read with a binary reader

**Comment by pbcornell** [comment] 2019-08-02 21:34
Unable to reproduce, closing.  Here's my attempt:

```javascript
let bytes = write(ion.makeTextWriter());
let ionText = String.fromCharCode.apply(null, bytes);
console.log('ionText: ' + ionText);

// read as text
read(ion.makeReader(ionText));
console.log();

// write as binary
let ionBinary = write(ion.makeBinaryWriter());
console.log('ionBinary: ' + toHexString(ionBinary));

// read as binary
read(ion.makeReader(ionBinary));


function write(w) {
    w.writeStruct();
    w.writeFieldName('false');
    w.writeInt(5);
    w.endContainer();
    w.close();
    return w.getBytes();
}

function read(r) {
    let t = r.next();
    console.log('t: ' + t.name);
    r.stepIn();
    t = r.next();
    console.log('t: ' + t.name + ', f: ' + r.fieldName() + ', v: ' + r.value());
    r.stepOut();
}

function toHexString(byteArray) {
    let sb = '';
    byteArray.forEach(b => {
        if (sb != '') { sb += ' ' }
        sb += ('0' + (b & 0xFF).toString(16)).slice(-2);
    });
    return sb;
}
```

produces:
```
ionText: {'false':5}
t: struct
t: int, f: false, v: 5

ionBinary: e0 01 00 ea eb 81 83 d8 87 b6 85 66 61 6c 73 65 d3 8a 21 05
t: struct
t: int, f: false, v: 5
```

**Closed by pbcornell** 2019-08-02 21:34 UTC
Labels: S, bug
